version: '2'
services:
  rasa:
    image: rasa-chatbot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    - ./models:/app/models
    - ./templates:/app/templates
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
    ports: '5006:5005'
    networks:
    - all


  rasa-actions:
    image: rasa-chatbot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    
